### ISSUE TITLE
SETUP @ricky0123/vad-react in Next js

### ISSUE THREAD

**Issue by rajukumar1995** [ricky0123/vad#106]
when i using  next js and implement then showing error  

app-index.tsx:26 Encountered an error while loading worklet. Please make sure the worklet vad.bundle.min.js included with @ricky0123/vad-web is available at the specified path:
        /vad.worklet.bundle.min.js
        If need be, you can customize the worklet file location using the `workletURL` option.

**Comment by Dmmoim** [comment]
it works for me.

Edit the next.config.mjs:
`import CopyWebpackPlugin from 'copy-webpack-plugin';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

export default {
  webpack: (config, { isServer }) => {
    if (!isServer) {
      config.plugins.push(
        new CopyWebpackPlugin({
          patterns: [
            {
              from: path.resolve(__dirname, 'node_modules/@ricky0123/vad-web/dist/vad.worklet.bundle.min.js'),
              to: path.resolve(__dirname, 'public/_next/static/chunks'),
            },
            {
              from: path.resolve(__dirname, 'node_modules/@ricky0123/vad-web/dist/silero_vad.onnx'),
              to: path.resolve(__dirname, 'public/_next/static/chunks'),
            },
            {
              from: path.resolve(__dirname, 'node_modules/onnxruntime-web/dist/ort-wasm-simd.wasm'),
              to: path.resolve(__dirname, 'public/_next/static/chunks'),
            },
            {
              from: path.resolve(__dirname, 'node_modules/onnxruntime-web/dist/ort-wasm.wasm'),
              to: path.resolve(__dirname, 'public/_next/static/chunks'),
            },
          ],
        }),
      );
    }
    return config;
  },
};
`

**Comment by wangtiger317** [comment]
it doesn't work for me.
my next js version is 13.
It doesn't copy files to _next/static/chunks directory when run

**Comment by wangtiger317** [comment]
I solved the issue

**Comment by CrashingTheCode** [comment]
I have same issue...
and I am running nextjs 14. 
@Dmmoim your solution only works on dev environment, when I try to build the project to run it on production it throws an error:
 Build error occurred
Error: You can not have a '_next' folder inside of your public folder. This conflicts with the internal '/_next' route. https://nextjs.org/docs/messages/public-next-folder-conflict
    at /Users/crash/Documents/Development/Organizoo/orga-nextjs/node_modules/next/dist/build/index.js:595:27
    at async Span.traceAsyncFn (/Users/crash/Documents/Development/Organizoo/orga-nextjs/node_modules/next/dist/trace/trace.js:154:20)
    at async build (/Users/crash/Documents/Development/Organizoo/orga-nextjs/node_modules/next/dist/build/index.js:366:9)
error Command failed with exit code 1.

**Comment by rahulbansal16** [comment]
I wrote a VAD to work with the web from scratch using ONNX Web and SILEROA VAD. Here is the repo.

https://github.com/DictationDaddy/VAD_WEB_DEMO

**Comment by theisof** [comment]
I gave up trying to get it to work with the bundler. The statically referenced file names seem to have changed in the packages since the documentation was written. Instead, I got it working in NextJS by including the files from the jsDelivr CDN and then casting the global types in my React code like this:

**_app.tsx**
```
  
<Script
  src="https://cdn.jsdelivr.net/npm/onnxruntime-web/dist/ort.js"
  strategy="beforeInteractive"
/>
<Script
   src="https://cdn.jsdelivr.net/npm/@ricky0123/vad-web@0.0.18/dist/bundle.min.js"
   strategy="beforeInteractive"
/>
```

**component.tsx**
```
import { type MicVAD } from "@ricky0123/vad-web";

useEffect(() => {
  const MicVad = (window as any).vad.MicVAD as typeof MicVAD;
},[])
```

> To get correct types, make sure the version number of the jsDeliver source and the npm package matches. 

Not the prettiest solution, but it should be slightly more stable than directly referencing dist files inside a peer dependency—I hope 😅

**Comment by iammakk** [comment]
> I solved the issue

did u setup ricky vad in next js . please help

**Comment by iammakk** [comment]
> I wrote a VAD to work with the web from scratch using ONNX Web and SILEROA VAD. Here is the repo.
> 
> https://github.com/DictationDaddy/VAD_WEB_DEMO

hey i need help . i want to setup vad with next js but the issue is. on rickyVad github examples i copy the next config but i get the error of the files in onnx-runtime web not found.
  {
            from: "./node_modules/onnxruntime-web/dist/ort-wasm.wasm",
            to: "static/chunks/[name][ext]",
          },
          {
            from: "./node_modules/onnxruntime-web/dist/ort-wasm-simd.wasm",
            to: "static/chunks/[name][ext]",
          },
          can u help please??

**Comment by rahulbansal16** [comment]
Hey, I have no idea how to use the Ricky VAD. Can you take a look at my repo and see how to use my repo? It's a Next.js example only.

**Comment by iammakk** [comment]
> Hey, I have no idea how to use the Ricky VAD. Can you take a look at my repo and see how to use my repo? It's a Next.js example only.

i cannot understand yours also.:(

**Comment by leafamrit** [comment]
I got it to work on NextJS 14+ somehow, here's what I did:
- Latest onnxruntime-web is at 1.19.2 as of today, and it does not have some .wasm files that I believe ricky-vad expects (based on the [nextjs example in this repo](https://github.com/ricky0123/vad/tree/master/examples/nextjs)
- I downgraded to [1.18.0](https://www.npmjs.com/package/onnxruntime-web/v/1.18.0), which does contain those files, then used the [next.config.js from the ricky-vad nextjs example](https://github.com/ricky0123/vad/blob/master/examples/nextjs/next.config.js), and changed the "to" paths to point to `/static/chunks/app/[name][ext]` directory:

```
const CopyPlugin = require("copy-webpack-plugin");

/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,

  webpack: (config, {}) => {
    config.resolve.extensions.push(".ts", ".tsx");
    config.resolve.fallback = { fs: false };

    config.plugins.push(
      new CopyPlugin({
        patterns: [
          // up to onnxruntime-web@1.18.0
          {
            from: "./node_modules/onnxruntime-web/dist/ort-wasm.wasm",
            to: "static/chunks/app/[name][ext]",
          },
          {
            from: "./node_modules/onnxruntime-web/dist/ort-wasm-simd.wasm",
            to: "static/chunks/app/[name][ext]",
          },
          {
            from: "node_modules/@ricky0123/vad-web/dist/vad.worklet.bundle.min.js",
            to: "static/chunks/app/[name][ext]",
          },
          {
            from: "node_modules/@ricky0123/vad-web/dist/*.onnx",
            to: "static/chunks/app/[name][ext]",
          },
        ],
      })
    );

    return config;
  },
};

module.exports = nextConfig;
```

- and the component is simply:
```
const vad = useMicVAD({
startOnLoad: true,
onSpeechEnd: (audio) => {
    console.log("user stopped talking");
},
});
```

Hope this helps.

**Comment by omegaDev001** [comment]
> Lo conseguí para trabajar en NextJS 14+ de alguna manera, esto es lo que hice:
> 
> * La última web onnxruntime está en 1.19.2 a partir de hoy, y no tiene algunos archivos .wasm que creo que espera ricky-vad (basado en el [ejemplo de nextJs en este repositorio](https://github.com/ricky0123/vad/tree/master/examples/nextjs))
> * Me rebajé a [1.18.0](https://www.npmjs.com/package/onnxruntime-web/v/1.18.0), que contiene esos archivos, luego usó el [next.config.js del ejemplo ricky-vad nextjs](https://github.com/ricky0123/vad/blob/master/examples/nextjs/next.config.js)y cambió los caminos "a" para señalar `/static/chunks/app/[name][ext]` directorio:
> 
> ```
> const CopyPlugin = require("copy-webpack-plugin");
> 
> /** @type {import('next').NextConfig} */
> const nextConfig = {
>   reactStrictMode: true,
> 
>   webpack: (config, {}) => {
>     config.resolve.extensions.push(".ts", ".tsx");
>     config.resolve.fallback = { fs: false };
> 
>     config.plugins.push(
>       new CopyPlugin({
>         patterns: [
>           // up to onnxruntime-web@1.18.0
>           {
>             from: "./node_modules/onnxruntime-web/dist/ort-wasm.wasm",
>             to: "static/chunks/app/[name][ext]",
>           },
>           {
>             from: "./node_modules/onnxruntime-web/dist/ort-wasm-simd.wasm",
>             to: "static/chunks/app/[name][ext]",
>           },
>           {
>             from: "node_modules/@ricky0123/vad-web/dist/vad.worklet.bundle.min.js",
>             to: "static/chunks/app/[name][ext]",
>           },
>           {
>             from: "node_modules/@ricky0123/vad-web/dist/*.onnx",
>             to: "static/chunks/app/[name][ext]",
>           },
>         ],
>       })
>     );
> 
>     return config;
>   },
> };
> 
> module.exports = nextConfig;
> ```
> 
> * y el componente es simplemente:
> 
> ```
> const vad = useMicVAD({
> startOnLoad: true,
> onSpeechEnd: (audio) => {
>     console.log("user stopped talking");
> },
> });
> ```
> 
> Espero que esto ayude.

Esto me funciono, muchas gracias

**Comment by leafamrit** [comment]
> do you succeed to handle the build to the production ? on dev server work fine but build process break my code
> 
> again and again i encounter an error while loading model file.
> 
> "Please make sure silero_vad.onnx, included with @ricky0123/vad-web, is available at the specified path: /models/silero_vad.onnx"
> 

I do have it running on production, I think the only thing I needed to add to make it work was to add the following to the patterns in CopyPlugin:
```
{
  from: "./node_modules/onnxruntime-web/dist/ort-wasm.wasm",
  to: "static/chunks/[name][ext]",
},
{
  from: "./node_modules/onnxruntime-web/dist/ort-wasm-simd.wasm",
  to: "static/chunks/[name][ext]",
},
{
  from: "node_modules/@ricky0123/vad-web/dist/vad.worklet.bundle.min.js",
  to: "static/chunks/[name][ext]",
},
{
  from: "node_modules/@ricky0123/vad-web/dist/*.onnx",
  to: "static/chunks/[name][ext]",
},
```

This is in addition to the existing patterns. 
It's creating duplicates - same files at 2 locations - but I was having trouble as the location VAD was expecting these files at was changing intermittently, especially on production build.

It never really expected the file at /models location for me, so I would not be able to comment. 
If it helps, the exact NextJS version I'm on is 14.2.13, and production deployment is on Vercel.

**Comment by ricky0123** [comment]
Hi all, I have made some important changes in the newest release. Please see [this section](https://docs.vad.ricky0123.com/user-guide/browser/#serving-the-workletonnxwasm-files) of the docs. Basically, by default now those files will be pulled from the CDN.

I also updated [nextjs example](https://github.com/ricky0123/vad/tree/master/examples/nextjs), which shows how to serve the files yourself instead of pulling them from the CDN. 

As some people have noted, it seems like certain newer versions of onnxruntime-web cause some issues with bundling in nextjs (and maybe other problems in general). I recommend specifically using version 1.14.0 of onnxruntime-web.

Let me know if you have any issues upgrading. The new version also allows you to play with the newest Silero model as described [here](https://docs.vad.ricky0123.com/user-guide/silero-v5/).
