### ISSUE TITLE
Error importing onnxruntime-node in Vue.js 2 with Webpack 4

### ISSUE THREAD

**Issue by Valterrsj** [ricky0123/vad#6]
Hello friend,

Niceee job!

I am trying to import the onnxruntime-node library in a Vue.js 2 component with Webpack 4, but I am getting the following error:

Uncaught Error: Cannot find module './browser/browser/onnxruntime_binding.node'
at webpackContextResolve (eval at ./node_modules/@ricky0123/vad/node_modules/onnxruntime-node/bin/napi-v3 sync recursive ^./././onnxruntime_binding.node$ (app~._i.js:21:1), <anonymous>:17:11)
at webpackContext (eval at ./node_modules/@ricky0123/vad/node_modules/onnxruntime-node/bin/napi-v3 sync recursive ^./././onnxruntime_binding.node$ (app~._i.js:21:1), <anonymous>:12:11)
at Object.eval (binding.js?a23c:9:1)
at eval (binding.js:11:30)
at ./node_modules/@ricky0123/vad/node_modules/onnxruntime-node/dist/binding.js (chunk-vendors~[._node_modules_@b.js](mailto:._node_modules_@b.js):616:1)
at webpack_require (app~._src_views_Layout_xxxxxx..js:871:30)
at fn (app~._src_views_Layout_xxxxxx..js:168:20)
at Object.eval (backend.js?497e:20:1)
at eval (backend.js:78:30)
at ./node_modules/@ricky0123/vad/node_modules/onnxruntime-node/dist/backend.js (chunk-vendors~[._node_modules_@b.js](mailto:._node_modules_@b.js):604:1)

**Comment by ricky0123** [comment]
Hi @Valterrsj. For Vue you should

1. install `@ricky0123/vad` and `onnxruntime-web`
1. import the vad package in your vue code like so
   ```typescript
   import { MicVAD, RealTimeVADOptions } from "@ricky0123/vad"
   // ...
   ```
1. configure webpack to copy the needed files to your output or dist directory as outlined [here](https://github.com/ricky0123/vad#bundler) for webpack 5.

You shouldn't add `onnxruntime-node` as a dependency and your code/webpack config shouldn't interact with it.

I realize now that the README may be unclear as to what import statement to use in a webpack-managed frontend product. 

Let me know if that clears things up or if you still encounter any problems

**Comment by Valterrsj** [comment]
Hi @ricky0123, 

Thank you for your prompt response!!

I have followed the steps you provided in your previous response and I am now encountering the error "_fastGlob.default.escapePath is not a function" when trying to import the package "@ricky0123/vad" in my code

**Comment by ricky0123** [comment]
Hi @Valterrsj, could you create a small project replicating the error or tell me more about your set up?

**Comment by ricky0123** [comment]
I've updated the [documentation](https://www.vad.ricky0123.com/docs/browser) to try to make things clearer. Feel free to re-open if you continue having issues.
